### ISSUE TITLE
Check whether demangled names are correct

### ISSUE THREAD

**Issue by kpp** [luser/rustfilt#12]
https://github.com/luser/rustfilt/blob/82d1e093a42bb83c47f96cc72a32e62d00a28dab/src/tests.rs#L8

I suggest you storing (mangled, demangled) names and check whether demangle(mangled) = demangled

**Comment by luser** [comment]
I think I skipped that level of testing since fundamentally we're using the `rustc-demangle` crate to do all the hard work. If there are errors demangling I'd expect them to be bugs in *that* crate. That being said for the "demangle symbols from a line surrounded by context" functionality it would probably be useful to test that we correctly demangle the symbols in context.

**Comment by kpp** [comment]
Thanks
